# Setup
title:          "tralsesec"
tagline:        "Operator // Researcher"
description:    "Offensive Security Researcher · Malware Developer & Analyst · Exploit Developer · CTF Player"
url:            "https://tralsesec.github.io" # Change if using a custom domain
baseurl:        "" # Keep empty if this is your main User Page (tralsesec.github.io). If it's a project page, use "/repo-name"

author:
  name:         "tralsesec"
  url:          "https://github.com/tralsesec"

paginate:       5

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom Collections
collections:
  anatomy-of-a-bug:
    output: true
    permalink: /anatomy-of-a-bug/:path/
  projects:
    output: true
    permalink: /projects/:path/
  ctfs:
    output: true
    future: true
    permalink: /ctfs/:path/

#kramdown:
#  input: GFM
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true  # <--- This turns on the numbers
#      span:
#        line_numbers: false
